from fastapi import FastAPI, Request, Form, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.responses import JSONResponse
from pydantic import BaseModel, HttpUrl
import asyncio
import re
from urllib.parse import urljoin, urlparse
from crawl4ai import AsyncWebCrawler
from crawl4ai.async_configs import BrowserConfig, CrawlerRunConfig
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def fix_malformed_urls(content: str, base_url: str) -> str:
    """
    Fix URLs with angle brackets like 'https://site.com/</path>'
    which are incorrectly generated by some markdown processors.
    """
    if not content:
        return content
    
    # Pattern to match URLs with angle brackets: https://site.com/</path>
    # This handles cases where relative URLs got wrapped in angle brackets
    pattern = r'(https?://[^\s<>]+)</([^>]+)>'
    
    def replace_url(match):
        base = match.group(1)
        path = match.group(2)
        # Ensure proper URL joining
        if path.startswith('/'):
            parsed = urlparse(base)
            fixed = f"{parsed.scheme}://{parsed.netloc}{path}"
        else:
            fixed = urljoin(base + '/', path)
        return fixed
    
    # Fix the malformed URLs
    fixed_content = re.sub(pattern, replace_url, content)
    
    # Also fix any remaining angle brackets around URLs in markdown links
    # Pattern: [text](<url>) -> [text](url)
    fixed_content = re.sub(r'\[(.*?)\]\(<([^>]+)>\)', r'[\1](\2)', fixed_content)
    
    return fixed_content

app = FastAPI(
    title="Web Scraper",
    description="Extract clean text content from URLs using crawl4ai",
    version="1.0.0"
)

app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

class ScrapeRequest(BaseModel):
    url: HttpUrl

class ScrapeResponse(BaseModel):
    url: str
    title: str
    content: str
    success: bool
    error: str | None = None

@app.get("/")
async def read_root(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})

@app.post("/api/scrape", response_model=ScrapeResponse)
async def scrape_url(scrape_request: ScrapeRequest):
    url = str(scrape_request.url)
    logger.info(f"Scraping URL: {url}")
    
    try:
        browser_config = BrowserConfig(
            headless=True,
            verbose=False
        )
        
        crawler_config = CrawlerRunConfig(
            word_count_threshold=10,
            excluded_tags=['nav', 'footer', 'aside', 'script', 'style'],
            remove_overlay_elements=True,
            process_iframes=False
        )
        
        async with AsyncWebCrawler(config=browser_config) as crawler:
            result = await crawler.arun(
                url=url,
                config=crawler_config
            )
            
            if result.success:
                # Try different content formats to get the cleanest output
                # Priority: fit_markdown > markdown > fit_html > cleaned_html
                content = None
                
                if hasattr(result, 'fit_markdown') and result.fit_markdown:
                    content = result.fit_markdown
                    logger.info(f"Using fit_markdown for {url}")
                elif result.markdown:
                    content = result.markdown
                    logger.info(f"Using markdown for {url}")
                elif hasattr(result, 'fit_html') and result.fit_html:
                    content = result.fit_html
                    logger.info(f"Using fit_html for {url}")
                elif result.cleaned_html:
                    content = result.cleaned_html
                    logger.info(f"Using cleaned_html for {url}")
                else:
                    content = "No content extracted"
                    logger.warning(f"No content found for {url}")
                
                # Fix malformed URLs with angle brackets
                if content and content != "No content extracted":
                    content = fix_malformed_urls(content, url)
                
                return ScrapeResponse(
                    url=url,
                    title=result.metadata.get("title", "No title"),
                    content=content,
                    success=True,
                    error=None
                )
            else:
                return ScrapeResponse(
                    url=url,
                    title="",
                    content="",
                    success=False,
                    error=result.error_message or "Unknown error occurred"
                )
                
    except Exception as e:
        logger.error(f"Error scraping {url}: {str(e)}")
        return ScrapeResponse(
            url=url,
            title="",
            content="",
            success=False,
            error=str(e)
        )

@app.get("/api/health")
async def health_check():
    return {"status": "healthy", "service": "web-scraper"}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
